### ISSUE TITLE
How to edit length and parts locally?

### ISSUE THREAD

**Issue by gxespino** [baxang/coupon-code#1]
Hello, I'm a rails noob and I got your coupon_code gem installed and it works! How do I edit the code lengths and parts locally?

**Comment by baxang** [comment]
Hi @gxespino,
I'm glad you tried my code.

You can change the number of parts of the generated code by passing an option hash value like: 

```
CouponCode.generate(parts: 4)
```

However changing each part's character length is not supported.

**Comment by gxespino** [comment]
Thank you!
